name: Generate QR Code
on: 
  issue_comment:
    types: [created]
jobs: 
  generate_qr_code:
    if: ${{ github.event.issue.title == 'QRCodeGenerator' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The comment is ${{ github.event.comment.body }}"
      - run: echo "The user is ${{ github.event.sender.login }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: pip install pillow qrcode==7.3.1
      - name: Generate QR code image
        id: generate_qr_code_image
        run: echo "::set-output name=image_markdown_code::$(python ${{ github.workspace }}/QRCodeGenerator/gen_qr_code.py --message '${{ github.event.comment.body }}' --local_repo_path '${{ github.workspace }}')"
      - name: Commit and upload the generated image
        run: |
          git config --local user.email "yanyuanmeng1996@qq.com"
          git config --local user.name "yym6472"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "Uploaded image"
          git push origin master
      - name: Submit image URI to issue (Through GitHub API)
        run: |
          echo "${{ steps.generate_qr_code_image.outputs.image_markdown_code }}"
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json' \
            --data '{"body": "The QR code for `${{ github.event.comment.body }}` is: \n${{ steps.generate_qr_code_image.outputs.image_markdown_code }}"}'