name: Generate QR Code
on: 
  issue_comment:
    types: [created]
jobs: 
  print_logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The comment is ${{ github.event.comment }}"
      - run: echo "The user is ${{ github.event.sender }}"