name: In Out
on: 
  issue_comment:
    types: [created]
jobs: 
  generate_static_html_files:
    if: ${{ github.event.issue.title == 'InOut' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The comment is ${{ github.event.comment.body }}"
      - run: echo "The user is ${{ github.event.sender.login }}"
      - uses: actions/checkout@v2
        with:
          repository: 'skycs608/skycs608.github.io'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Generate Static HTML Files
        id: generate_static_html_files
        run: python ${{ github.workspace }}/main.py --message '${{ github.event.comment.body }}' --local_repo_path '${{ github.workspace }}'
      - name: Commit and upload the generated image
        run: |
          git config --local user.email "skycs608@gmail.com"
          git config --local user.name "skycs608"
          git remote set-url origin https://skycs608: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@github.com/skycs608/skycs608.github.io
          git add .
          git commit --allow-empty -m "Generated static files"
          git push origin master